#!/bin/bash

# If bootstrap openssl or curl is updated in a new base version, we want to rebuild those in i.e. selfupdate.
# If they are already present, no need to rebuild the same bootstrap softwares.
# Selfupdate runs bootstrap blindly, so this is a good solution to 'notify' that new bootstrap software is available.
# Regardless SSL certs are updated as that takes no time at all to do.
# This can be forced 
force_bootstrap_rebuild=false

if [ "$EUID" -ne 0 ]; then
    echo "Error: run "$0" with sudo or root"
    exit 1
fi

cd "$(dirname "$0")"
echo $PWD

# Mac $PATH, we don't want anything from anywhere else.
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
# This could be setup to allow for different prefixes, but right now it expects a location that requires sudo to write into.
prefix=/opt/local
bootstrap=$prefix/bootstrap

# Last version that builds without requiring a newer perl (5.8.6). Will probably# change this to 1.1.1 to get TLS v1.3 support and just add perl to bootstrap.
ssl=openssl-1.0.2u

# Last version to support OpenSSL v1.x.
curl=curl-8.17.0

certs=cacert-2026-08-13.pem

# Straight from open source apple for 10.5.8, builds without modification.
make=gnumake-119

# Latest versions:
bzip=bzip2-1.0.8
gzip=gzip-1.15

# Same versions as 10.5.8 (but we don't use open source apple releases from
# Apple (yet) as they need quite a bit of patching.
tar=tar-1.15.1
libarchive=libarchive-2.8.3

arch=$(arch)
number_of_cpus=$(sysctl -n hw.ncpu)
tmp=$(mktemp -d /var/tmp/tigerports-bootstrap.XXX)
# Because this isn't /tmp, we need to make it rwx:
chmod -R 777 $tmp

# When this script exits, automatically delete the temp directory.
cleanup() 
{ 
    if [[ -e $tmp ]]; then
        echo "Clearing temp files..."  
        rm -rf $tmp   
    fi
}
trap cleanup EXIT

# Sets prefix, curl, and make to be used.
# We simulate leopard (and it didn't even really change even at sierra).
build_base() {
    ./configure \
        --prefix=$prefix \
        --with-curlprefix=$bootstrap \
        --with-gnumake=$bootstrap/bin/make \
        --with-make=$bootstrap/bin/make \
        --with-bzip2_bin=$bootstrap/bin/bzip2 \
        --with-tar=$bootstrap/bin/bsdtar \
        --with-gnutar=$bootstrap/bin/tar

    make_and_install
    
    if [[ ! -e "~/.bash_profile" ]]; then
        echo "source $prefix/share/macports/setupenv.bash" > ~/.bash_profile
        echo "Wrote $HOME/.bash_profile, start a new terminal session for it to apply"
    else
	echo "Existing $HOME/.bash_profile already exists, so it has not been replaced. If you wish for this installer to install $HOME/.bash_profile, please delete your existing $HOME/.bash_profile and run "$0" again."
    fi
}

install_certs() {
    mkdir -p $bootstrap/etc/ssl
    cp -v bootstrap-src/$certs $bootstrap/etc/ssl/cacert.pem
    echo "$certs installed!"
}

if [[ "$arch" == ppc ]]; then
    ssl_config_val=darwin-ppc-cc
elif [[ "$arch" == i386 ]]; then
    ssl_config_val=darwin-i386-cc
else
    echo "Error: unsupported $arch"
    exit 1
fi

# CA certificates extracted from Mozilla 
# https://curl.se/docs/caextract.html
# Note: These can be updated via http. Perhaps implement that.
if [[ -e "$bootstrap/bin/make" ]] && \
    [[ -e "$bootstrap/bin/openssl" ]] && \
    [[ -e "$bootstrap/bin/curl" ]] && \
    [[ -e "$bootstrap/bin/bzip2" ]] && \
    [[ -e "$bootstrap/bin/gzip" ]] && \
    [[ -e "$bootstrap/bin/tar" ]] && \
    [[ -e "$bootstrap/bin/bsdtar" ]] && \
    [[ "$force_bootstrap_rebuild" = "false" ]] && \
    [[ "$1" != "-f" ]]; then
    echo "Skipping full rebuild of bootstrap software as it is not needed."
    echo "Note: if you want to force rebuilding all bootstrap software anyways, pass the -f arg:"
    echo "./bootstrap -f"
    install_certs
    build_base
    exit 0
else
    # Delete bootstrap subdir to start clean.
    rm -rf $bootstrap
    install_certs
fi

echo "Building bootstrap..."
set -e

make_and_install() {
    make -j$number_of_cpus && make install PREFIX=$bootstrap
}

# Patch for patch, bug for bug compatible, directly from open source apple circa 2009 for leopard:
# https://web.archive.org/web/20110707153724/https://opensource.apple.com/release/mac-os-x-1058/
# This uses Apple build infra, so make clean just makes sure /tmp/gnumake is clear.
tar zxf bootstrap-src/$make.tar.gz -C $tmp
(
    cd $tmp/$make
    make clean
    make
    mkdir $bootstrap/bin
    cp -v /tmp/gnumake/Build/make $bootstrap/bin/make
)

# We want to use the new Make for better parallel support.
export PATH=$bootstrap/bin:/bin:/sbin:/usr/bin:/usr/sbin
which make


tar zxf bootstrap-src/$bzip.tar.gz -C $tmp
(
    cd $tmp/$bzip

    make -j$number_of_cpus
    make install PREFIX=$bootstrap
)

tar zxf bootstrap-src/$gzip.tar.gz -C $tmp
(
    cd $tmp/$gzip
    ./configure \
        --prefix=$bootstap

     make_and_install
)

# Goes off '$PATH' to pull gzip/bzip2, so we already fixed that to use newer make.
tar zxf bootstrap-src/$tar.tar.gz -C $tmp
(
    cd $tmp/$tar
    ./configure \
        --prefix=$bootstrap

    make_and_install
)

# This actually is the bsdtar command for 10.5+.
tar zxf bootstrap-src/$libarchive.tar.gz -C $tmp
(
    cd $tmp/$libarchive
    ./configure \
        --prefix=$bootstrap \

    make_and_install
)

# OpenSSL 1.1.1x needs Perl 5.8.6 which tiger does not have, and bootstrap doesn't build (yet).
# OpenSSL 1.0.2 gets us TLSv1.2, which is good enough for gitlab, github, and most distfile sites for now in 2026.
# OpenSSL 1.1.1x will get us to TLSv1.3 if/when that is implemented in bootstrap.
# Using install_sw target skips docs that we don't need and take forever to generate.
# Mac OS X needs Configure not config, so we need to pass it the value it wants.
# Tiger Intel fails on asm so disable it.
# Tiger fails on async so disable it.
# Tiger fails on threads so disable it.
# Mac OS X ships with shared zlib.
# Note: it asks to make depend but we don't have makedepend installed and it's not needed.
echo "Extracting $ssl.tar.gz..."
tar zxf bootstrap-src/$ssl.tar.gz -C $tmp
(
    cd $tmp/$ssl

    ./Configure \
        --prefix=$bootstrap \
        --openssldir=$bootstrap \
        enable-shared \
        zlib-dynamic \
	no-async \
	no-threads \
        no-asm \
        $ssl_config_val

    make -j$number_of_cpus
    make install_sw
)

# Last version of Curl that can use OpenSSL 1.1.1.x.
# The last version of Curl that can use Tiger system zlib is 8.11.0, but it segfaults with it enabled.
# Bootstrap doesn't (yet) build zlib, so disable zlib for now.
# Disabble libpsl because Mac OS X doesn't ship with it. It can be built even on tiger but bootstrap doesn't.
echo "Extracting $curl.tar.bz2..."
tar jxf bootstrap-src/$curl.tar.bz2 -C $tmp
(
    cd $tmp/$curl
    ./configure \
        CPPFLAGS="-I$bootstrap/include" \
        LDFLAGS="-L$bootstrap/lib" \
        --prefix=$bootstrap \
        --with-ssl=$bootstrap \
        --with-ca-bundle=$bootstrap/etc/ssl/cacert.pem \
        --without-zlib \
        --without-libpsl \
        ac_cv_path_PKGCONFIG="no"

    make_and_install
)

build_base
