#!/bin/bash

prefix=/opt/local

cd "$(dirname "$0")

if [[ ! -e "~/.bash_profile" ]]; then                     
    echo "source $prefix/share/macports/setupenv.bash" > ~/.bash_profile
    echo "Wrote $HOME/.bash_profile, starting  a new shell for it to apply"
    bash
else
    echo "Existing $HOME/.bash_profile already exists, so it has not been replaced. If you wish to overwrite $HOME/.bash_profile:"
    echo "mv $HOME/.bash_profile $HOME/.bash_profile.orig"
    echo ""$0""
fi
