#!/bin/bash

base_sec=~/dev/tigerports-keys/tigerports-base-2027.sec
version=2.12.04.004

if [[ ! -e "$base_sec" ]]; then
    echo "Error: can not find $base_sec"
    exit 1
fi

read -p "this will commit a $version tag and new commit to git, press any key to procceed"

echo "Using version: $1"

echo "Updating tigerports-base version in config/macports_version..."
echo -e "$version\n" > config/macports_version
cat config/macports_version

echo "Updating tigerports-base version in config/RELEASE_URL..."
echo -e "https://github.com/alex-free/tigerports-base/releases/tag/v$version\n" > config/RELEASE_URL
cat config/RELEASE_URL

echo "Building configure and manpages..."
./autogen.sh
./standard_configure.sh
make -C doc/ clean all \
    ASCIIDOC=/opt/local/bin/asciidoc \
    XSLTPROC=/opt/local/bin/xsltproc \
    DOCBOOK_XSL=/opt/local/share/xsl/docbook-xsl-nons/manpages/docbook.xsl

echo "Building release tarballs..."
rm configure~
git add .
git commit -m "v$version"
git push
git tag v$version
git push origin v$version

echo "Building release tarballs..."
make -C vendor
make dist DISTVER=$version DISTKEY=$base_sec
